name: 'Terraform PR Commenter'
description: 'Adds opinionated comments to a PR from Terraform fmt/init/plan output'
author: 'Rob Burger'
branding:
  icon: 'git-pull-request'
  color: 'purple'
inputs:
  commenter_type:
    description: 'The type of comment. Options: [fmt, init, plan]'
    required: true
  commenter_input:
    description: 'The comment to post from a previous step output'
    required: true
  commenter_exitcode:
    description: 'The exit code from a previous step output'
    required: true
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.commenter_input }} >> tf.out
    - uses: 'docker'
      image: 'Dockerfile'
      args:
       - ${{ inputs.commenter_type }}
       - tf.out
       - ${{ inputs.commenter_exitcode }}
