name: 'Terraform PR Commenter'
description: 'Adds opinionated comments to a PR from Terraform fmt/init/plan output'
author: 'Rob Burger'
branding:
  icon: 'git-pull-request'
  color: 'purple'
inputs:
  commenter_type:
    description: 'The type of comment. Options: [fmt, init, plan]'
    required: true
  commenter_input:
    description: 'The comment to post from a previous step output or a tfplan file'
    required: true
  commenter_exitcode:
    description: 'The exit code from a previous step output'
    required: true
  terraform_version:
    description: 'The version of terraform with which a plan was generated'
    required: false
    default: "1.0.6"
runs:
  using: "composite"
  steps:
    - name: Build commenter docker image
      # append branch with a pound (#) if developing.  e.g., `commenter.git#my-branch`
      run: docker build --build-arg TERRAFORM_VERSION=${{ inputs.terraform_version }} -t commenter https://github.com/GetTerminus/terraform-pr-commenter.git
      shell: bash
    - name: Run commenter image (plan)
      env:
        COMMENTER_INPUT: ${{ inputs.commenter_input }}
        GITHUB_EVENT: ${{ toJSON(github.event) }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_KEY }}
      run: |
        docker run \
        -e GITHUB_TOKEN \
        -e TF_WORKSPACE \
        -e EXPAND_SUMMARY_DETAILS \
        -e HIGHLIGHT_CHANGES \
        -e GITHUB_EVENT \
        -e COMMENTER_INPUT \
        -e AWS_ACCESS_KEY_ID \
        -e AWS_SECRET_KEY \
        -e AWS_SECRET_ACCESS_KEY \
        -e AWS_REGION \
        -e COMMENTER_DEBUG \
        -e COMMENTER_ECHO \
        -v "$(pwd)"/:/workspace \
        commenter ${{ inputs.commenter_type }} nop ${{ inputs.commenter_exitcode }}
      shell: bash
      if: ${{ inputs.commenter_type == 'plan' }}
    - name: Run commenter image (non-plan)
      env:
        COMMENTER_INPUT: ${{ inputs.commenter_input }}
        GITHUB_EVENT: ${{ toJSON(github.event) }}
      run: |
        docker run \
        -e GITHUB_TOKEN \
        -e TF_WORKSPACE \
        -e EXPAND_SUMMARY_DETAILS \
        -e HIGHLIGHT_CHANGES \
        -e GITHUB_EVENT \
        -e COMMENTER_INPUT \
        commenter ${{ inputs.commenter_type }} nop ${{ inputs.commenter_exitcode }}
      shell: bash
      if: ${{ inputs.commenter_type != 'plan' }}

